export async function getTickets(): Promise<{
    tickets: Ticket[]
}> {
    return {
        tickets: [
            {
                id: "f47ac10b-58cc-4372-a567-0e02b2c3d479",
                type: "bug",
                title: "404 Error on Payment Page",
                description: "Users receive a 404 error when redirecting to the payment page after cart validation. Problem occurred after the latest update.",
                priority: "critical",
                lifetime: 5000,
                author: {
                    firstname: "Sophie",
                    lastname: "Martin",
                    position: "QA Engineer",
                },
            },
            {
                id: "550e8400-e29b-41d4-a716-446655440000",
                type: "feature",
                title: "Add Two-Factor Authentication",
                description: "Implement two-factor authentication via SMS or mobile app to enhance user account security.",
                priority: "high",
                lifetime: 10000,
                author: {
                    firstname: "Lucas",
                    lastname: "Dubois",
                    position: "Security Engineer",
                },
            },
            {
                id: "7c9e6679-7425-40de-944b-e07fc1f90ae7",
                type: "support",
                title: "Calendar Synchronization Issue",
                description: "Multiple users report synchronization issues between the application calendar and Google Calendar.",
                priority: "medium",
                lifetime: 20000,
                author: {
                    firstname: "Emma",
                    lastname: "Bernard",
                    position: "Support Technique",
                },
            },
            {
                id: "8c9e6679-7425-40de-944b-e07fc1f90ae8",
                type: "technical",
                title: "SQL Query Optimization",
                description: "Queries on the orders table are taking too long. Need to optimize indexes and queries to improve performance.",
                priority: "high",
                lifetime: 10000,
                author: {
                    firstname: "Thomas",
                    lastname: "Petit",
                    position: "Lead Developer",
                },
            },
            {
                id: "9c9e6679-7425-40de-944b-e07fc1f90ae9",
                type: "bug",
                title: "Mobile Display Error",
                description: "The dropdown menu doesn't display correctly on iOS devices in landscape mode.",
                priority: "medium",
                lifetime: 20000,
                author: {
                    firstname: "Julie",
                    lastname: "Moreau",
                    position: "Frontend Developer",
                },
            },
            {
                id: "ac9e6679-7425-40de-944b-e07fc1f90aea",
                type: "feature",
                title: "Export Data to PDF",
                description: "Add the ability to export monthly reports to PDF format with custom layout.",
                priority: "low",
                lifetime: 30000,
                author: {
                    firstname: "Pierre",
                    lastname: "Durand",
                    position: "Product Owner",
                },
            },
            {
                id: "bc9e6679-7425-40de-944b-e07fc1f90aeb",
                type: "support",
                title: "Password Reset Issue",
                description: "Password reset emails are not being received by users with @hotmail.fr addresses.",
                priority: "high",
                lifetime: 10000,
                author: {
                    firstname: "Marie",
                    lastname: "Laurent",
                    position: "Support Manager",
                },
            },
            {
                id: "cc9e6679-7425-40de-944b-e07fc1f90aec",
                type: "technical",
                title: "Node.js Security Update",
                description: "Urgent update required to fix a critical security vulnerability in the current Node.js version.",
                priority: "critical",
                lifetime: 5000,
                author: {
                    firstname: "Alexandre",
                    lastname: "Robert",
                    position: "DevOps Engineer",
                },
            },
            {
                id: "dc9e6679-7425-40de-944b-e07fc1f90aed",
                type: "bug",
                title: "Incorrect Discount Calculation",
                description: "The system calculates discounts incorrectly when multiple promotional codes are applied simultaneously.",
                priority: "high",
                lifetime: 10000,
                author: {
                    firstname: "Céline",
                    lastname: "Lefebvre",
                    position: "Backend Developer",
                },
            },
            {
                id: "ec9e6679-7425-40de-944b-e07fc1f90aee",
                type: "feature",
                title: "LinkedIn API Integration",
                description: "Allow users to connect and share content through their LinkedIn account.",
                priority: "medium",
                lifetime: 20000,
                author: {
                    firstname: "Nicolas",
                    lastname: "Garcia",
                    position: "Integration Specialist",
                },
            },
            {
                id: "fc9e6679-7425-40de-944b-e07fc1f90aef",
                type: "support",
                title: "Invoice Printing Issue",
                description: "A4 format invoices show layout problems when printing.",
                priority: "low",
                lifetime: 30000,
                author: {
                    firstname: "Sarah",
                    lastname: "Michel",
                    position: "Customer Support",
                },
            },
            {
                id: "gc9e6679-7425-40de-944b-e07fc1f90aeg",
                type: "technical",
                title: "Database Migration",
                description: "Planning and execution of database migration to PostgreSQL 14.",
                priority: "medium",
                lifetime: 20000,
                author: {
                    firstname: "David",
                    lastname: "Simon",
                    position: "Database Administrator",
                },
            },
        ],
    };
}
