import type {Metadata} from "next";
import {Kanit} from "next/font/google";
import {PropsWithChildren} from "react";
import "./globals.css";

const kanit = Kanit({
	weight: ["400", "600"],
	subsets: ["latin"],
});

export const metadata: Metadata = {
	title: "ECV - Project Manager",
	description: "Generated by create next app",
};

export default function RootLayout({children}: Readonly<PropsWithChildren>) {
	return (
		<html lang="en">
			<body className={`${kanit.className} antialiased`}>{children}</body>
		</html>
	);
}
